/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class papiJ */

#ifndef _Included_papiJ
#define _Included_papiJ
#ifdef __cplusplus
extern "C" {
#endif
#undef papiJ_PAPI_VER_CURRENT
#define papiJ_PAPI_VER_CURRENT 83886080L
/*
 * Class:     papiJ
 * Method:    PAPI_JNI_library_init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_papiJ_PAPI_1JNI_1library_1init
  (JNIEnv *, jobject, jint);

/*
 * Class:     papiJ
 * Method:    PAPI_JNI_threads_init
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_papiJ_PAPI_1JNI_1threads_1init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     papiJ
 * Method:    PAPI_JNI_start
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_papiJ_PAPI_1JNI_1start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     papiJ
 * Method:    PAPI_JNI_stop
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_papiJ_PAPI_1JNI_1stop
  (JNIEnv *, jobject, jstring);

/*
 * Class:     papiJ
 * Method:    PAPI_JNI_dumpMetrics
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_papiJ_PAPI_1JNI_1dumpMetrics
  (JNIEnv *, jobject);

/*
 * Class:     papiJ
 * Method:    f
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_papiJ_f
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
